export const ActionType = {
    SET_CHARACTERS :"SET_CHARACTERS",
    SELECTED_CHARACTER : "SELECTED_CHARACTER",
    REMOVE_SELECTED_CHARACTER : "REMOVE_SELECTED_CHARACTER",
    SET_CHARACTERS_INFO: "SET_CHARACTERS_INFO",
    FILTER_CHARACTERS:"FILTER_CHARACTERS",
    PER_PAGE_CHARACTERS:"PER_PAGE_CHARACTERS",
    SET_CHARACTERS_PG_NUM: "SET_CHARACTERS_PG_NUM",
    SET_CHARACTERS_PG_NEXT: "SET_CHARACTERS_PG_NEXT",
    SET_CHARACTERS_PG_PREV: "SET_CHARACTERS_PG_PREV",
    SET_CHARACTERS_SEARCH:"SET_CHARACTERS_SEARCH",
    SET_CHARACTERS_PG_NUM_ONE:"SET_CHARACTERS_PG_NUM_ONE",
    SET_CHARACTERS_FILTER: "SET_CHARACTERS_FILTER",
    SET_CHARACTERS_GEN_FILTER:"SET_CHARACTERS_GEN_FILTER"

};