export const ActionType = {
    SET_CHARACTERS :"SET_CHARACTERS",
    SELECTED_CHARACTER : "SELECTED_CHARACTER",
    REMOVE_SELECTED_CHARACTER : "REMOVE_SELECTED_CHARACTER",
    SET_CHARACTERS_INFO: "SET_CHARACTERS_INFO",
    FILTER_CHARACTERS:"FILTER_CHARACTERS",
    PER_PAGE_CHARACTERS:"PER_PAGE_CHARACTERS"

};